### PR TITLE
use port from config to perform health check

### PR DESCRIPTION
**Pull request by masterobiwan**

### CODE REVIEW

**Comment by tchiotludo** [comment]
I don't think this one could work on every case, not all the people have the configuration files with that properties (depending on they deploy it). 
I think we could assume a fixed port on this one (like on the helm charts)

**Comment by masterobiwan** [comment]
Fair point. I pushed a commit which provides a possible solution for this. No worries if you prefer to keep the fixed port.

**Comment by masterobiwan** [comment]
Also I could maybe fix the version of yq to use, to make sure the behaviour when the field is not found in yaml never change.

**Comment by tchiotludo** [comment]
@masterobiwan : still want to improve it?

**Pull request closed without merging**
