### PR TITLE
[OIDC] Support for the "Groups field or username field which be inside other fields" case

### PR DESCRIPTION
**Pull request by dongockien92**
In some cases, the groups-field or username-field can be inside other fields.

Ex: The "Token Claim Name" setting on Keycloak 20 has default value is "realm_access.roles"
image

The roles property will be inside the realm_access property
image

### CODE REVIEW

**Comment by tchiotludo** [comment]
Hey !! 
- Can you update since there is a conflict? 
- Can you add a relevant unit test please? I'm not sure to understand perfectly!

**Comment by tchiotludo** [comment]
perfect for the rebase, just missing a unit test and it's ok for me!

**Comment by dongockien92** [comment]
Hi @tchiotludo, I'm creating UT, I'll inform you when I completed it.

**Comment by dongockien92** [comment]
@tchiotludo I pushed UT, please help to take a look.

**Pull request merged**
