### PR TITLE
Improve the docker-compose environment

### PR DESCRIPTION
**Pull request by ankon**
Bunch of fixes and improvements I needed to make the docker-compose environment work smoothly

Note-worthy:
* https://github.com/tchiotludo/akhq/commit/42487c1461d196c1a1cf07a373dce6dd0befe6fd removes the odd IP address that was hard-coded. I couldn't find a reference to this anywhere else, but I may have missed something here.
* I think it would be good to tie the confluentinc/* images to a specific version of the Confluent Platform, to avoid unintentional breakages such as the one fixed by https://github.com/tchiotludo/akhq/commit/a15f93b49302d2e27853aa77aaccf675c21d0ac4

### CODE REVIEW

**Comment by tchiotludo** [comment]
The special `127.11.8.17` is a hack on linux that allow to listen on same port with multiple ip (mostly multiple docker in my case). 
Just add in `/etc/hosts` an alias, and don't bother with with available port on your machine. 
Since I don't use anymore the docker-compose this don't mind to remove this 

for my knowledge: `zookeeper-data:/var/lib/zookeeper/data:Z` 
What is the `Z` you add everywhere ?

**Comment by ankon** [comment]
> Since I don't use anymore the docker-compose this don't mind to remove this

Hmm. In that case I would actually propose to drop that completely. For development I suspect it should be easy enough to just run the two parts separately in your IDE (JVM backend + webpack dev server), and just providing a basic docker-compose setup for zookeeper + kafka should then be enough.

> Just add in /etc/hosts an alias, and don't bother with with available port on your machine.

Fair enough, could do that and add it to the documentation. I mainly don't like spending time working out why the documentation for development setup won't work when I come back to a project after a while -- I want to get to doing stuff! :)

> for my knowledge: zookeeper-data:/var/lib/zookeeper/data:Z
> What is the Z you add everywhere ?

This is telling docker how it should handle SELinux labels on the directories. 'z' means "allow this directory be shared by multiple containers if needed", while 'Z' means "only allow this one container to access it". If SELinux isn't enabled then these flags won't do anything.

From [docker-run(1)](https://docs.docker.com/engine/reference/commandline/run/):
> Labeling systems like SELinux require that proper labels are placed on volume content mounted into a container. Without a label, the security system might prevent the processes running inside the container from using the content. By default, Docker does not change the labels set by the OS.
> 
> To change the label in the container context, you can add either of two suffixes :z or :Z to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all containers to read/write content. The Z option tells Docker to label the content with a private unshared label. Only the current container can use a private volume.

**Comment by tchiotludo** [comment]
Thanks for all the detailed clarification, I don't have such knowledge on Docker (SELinux is a word I that I don't take time to look at).
I also think an backend server and a `npm run start` is fine but people may prefer docker-compose so I merge it for this guys.

**Comment by Grishnackh** [comment]
@tchiotludo Could you please point out what you do to get AKHQ locally working for development purposes? When I start the project locally (per gradle task _application/run_ or as IntelliJ IDEA build configuration of type _Application_ on class `org.akhq.App`, I get the following output:

> Task :App.main()
2021-02-08 21:26:59,766 INFO  main       i.m.runtime.Micronaut      Startup completed in 2506ms. Server Running: http://localhost:8080
2021-02-08 21:27:48,743 INFO  r-thread-1 org.akhq.log.access        [Date: 2021-02-08T21:27:48.3583598+01:00] [Duration: 416 ms] [Url: GET /] [Status: 307] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,788 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.7863468+01:00] [Duration: 1 ms] [Url: GET /ui] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,893 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.8899247+01:00] [Duration: 3 ms] [Url: GET /ui/ui/static/css/2.7caccc14.chunk.css] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,914 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9143521+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/2.a6ffe02f.chunk.js] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,919 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9192378+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/main.91579e51.chunk.css] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,923 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9221696+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/main.223782d5.chunk.js] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,968 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9671205+01:00] [Duration: 0 ms] [Url: GET /ui/ui/favicon.ico] [Status: 200] [Ip: /127.0.0.1] [User: -]

When I open the link for AKHQ, a blank/white screen is shown. The developer console output is as follows:

> Task :App.main()
2021-02-08 21:26:59,766 INFO  main       i.m.runtime.Micronaut      Startup completed in 2506ms. Server Running: http://localhost:8080
2021-02-08 21:27:48,743 INFO  r-thread-1 org.akhq.log.access        [Date: 2021-02-08T21:27:48.3583598+01:00] [Duration: 416 ms] [Url: GET /] [Status: 307] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,788 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.7863468+01:00] [Duration: 1 ms] [Url: GET /ui] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,893 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.8899247+01:00] [Duration: 3 ms] [Url: GET /ui/ui/static/css/2.7caccc14.chunk.css] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,914 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9143521+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/2.a6ffe02f.chunk.js] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,919 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9192378+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/css/main.91579e51.chunk.css] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,923 INFO  pGroup-1-6 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9221696+01:00] [Duration: 0 ms] [Url: GET /ui/ui/static/js/main.223782d5.chunk.js] [Status: 200] [Ip: /127.0.0.1] [User: -]
2021-02-08 21:27:48,968 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-02-08T21:27:48.9671205+01:00] [Duration: 0 ms] [Url: GET /ui/ui/favicon.ico] [Status: 200] [Ip: /127.0.0.1] [User: -]

What am I doing wrong, what is missing?

**Comment by tchiotludo** [comment]
The better is to start:  
-  the backend  with intellij running `org.akhq.App` 
- the front end with `npm run start` 

After this the ui is working on  `localhost:3000`

**Comment by Grishnackh** [comment]
Thank you @tchiotludo, this worked. I consider this a very valuable information. Don't you think it would be good to have this instructions noted in the development chapter of the README?

**Comment by tchiotludo** [comment]
Agree with that, @Grishnackh fell free to add a PR about that 👍

**Pull request merged**
