### PR TITLE
 refacto-pagination-and-query-parem-page 

### PR DESCRIPTION
**Pull request by PLarboulette**
Hello, 

I close the other PR. My first tests with the query param page seems to be good but I have to test it more to be sure.

### CODE REVIEW

**Comment by PLarboulette** [comment]
My IntelliJ broke the formatting of the files, I will try to fix it

**Comment by PLarboulette** [comment]
Old PR : https://github.com/tchiotludo/akhq/pull/634

**Comment by tchiotludo** [comment]
hi @PLarboulette, it's seems to be perfect ! 
Can you just remove the formatting noise please ? 
thanks

**Comment by PLarboulette** [comment]
Hello, 

Yes, sorry, it's better I think. I don't know but my IntelliJ breaks all the files, I will search why :(

**Pull request merged**
