### PR TITLE
ACL rewrite

### PR DESCRIPTION
**Pull request by AlexisSouquiere**
- [x] New authentication based on https://github.com/tchiotludo/akhq/discussions/523#discussioncomment-5752664
- [x] Add default roles / groups in application.yaml
- [x] Unit/integration tests
- [x] Documentation

New feature:
- [x] Support Micronaut security.authentication with bearer value as well as cookie. 
I saw that with a lot of regexp in the old authentication we can have a problem (auth failed) if the JWT token size is more than 4Ko (size limit of a cookie)

### CODE REVIEW

**Comment by AlexisSouquiere** [comment]
@tchiotludo ready for review !

**Comment by tchiotludo** [comment]
OMG! 100 files! 
please let me try to find some time to review that :exploding_head:

**Review by tchiotludo — CHANGES_REQUESTED** [review]
First review quickly (functional test), it seems to works really well !!!! :clap: :clap: :clap: :clap: :clap: 
Everything seems to be ok at first overview :clap: :clap: :clap: :clap: 
I need to validate some others features not tested for now (oidc, external) 

In a meantime, I found some enhancement : 
- Can you filter the cluster list based on the acls on the left menu?
- The [application.example](https://github.com/AlexisSouquiere/akhq/blob/cc20b747e5b7b95e269747e3d15ea47ec9da341d/application.example.yml#L196) is still with the old format

**Comment by AlexisSouquiere** [comment]
Thanks ! 😄 
Good comment I'll update these 2 points tomorrow

**Comment by AlexisSouquiere** [comment]
@tchiotludo I did the requested changes. We have deployed this branch on an dev environment to test the external claim provider too (provided by our ns4kafka tool) and it's working fine. I just fixed an issue linked to the bearer auth but there is no other issues till now

**Comment by ebrard** [comment]
@tchiotludo Any idea when this will be GA? Version 0.24 is older than this change I think. Thanks :D

**Comment by tchiotludo** [comment]
@ebrard I said soon since months, but I struggling finding time :cry:

**Comment by ebrard** [comment]
What is required to publish a version? Can I help you in any way?

**Comment by tchiotludo** [comment]
At first, I would love to update javascript dependencies, but seems to be a long task :cry:

**Comment by AlexisSouquiere** [comment]
I can find some time to check that. Not sure how long it can takes but I'll try to help on it

**Pull request merged**
