### PR TITLE
Support JSONSchema while producing message

### PR DESCRIPTION
**Pull request by txs4444**
Currently it is not possible to produce message to a topic while JSON Schema is chosen as key or value schema.
For producing message to a topic `RecordRepository` is used. In case schema id was present `AvroSchemaSerializer` was used regardless of schema type.

`RecordWithSchemaSerializerFactory` was introduced to take care of fetching schema from schema registry and create proper serializer. AvroSerializer is no longer responsible for fetching schema itself - it is not longer a bean but it is created on demand for specific schema.

A test not related to the functionality (`SchemaRegistryRepositoryTest#register`) was change because it was influenced by adding schema to schema registry by new `RecordRepositoryTest`

### CODE REVIEW

**Comment by tchiotludo** [comment]
hi @txs4444 ! 
amazing hard work here !! thanks :+1: 
Will need some time to review and to test, since I never used schema registry with JSON, sorry for that !

**Comment by txs4444** [comment]
hi @tchiotludo,
You're welcome. Useful tool.

Yes, sure. Let me know if you need some help while testing this.

**Comment by tchiotludo** [comment]
First try seems to works quite well : 
- I've added the ability to create json schema [here](https://github.com/tchiotludo/akhq/commit/f73ddb21c617efedcb6e5f2a33f54a49f494061a)
- I was able to produce with a json schema. 
- Json Schema is validated 

Seems to be good work here. 

Just the unit test failed, all the count is wrong since you have added a topic, can you fix it ?

**Comment by txs4444** [comment]
Sure, I'll fix them. Although it make take a while. When I build it locally only one test fails.
```
  org.akhq.controllers.SchemaControllerTest

    ✔ listApi() (2.2s)

  203 passing (2m 33s)
  4 pending
  1 failing


208 tests completed, 1 failed, 4 skipped
There were failing tests. See the report at: file:///home/ratatoskr/src/txs4444/akhq/build/reports/tests/test/index.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5m 4s
22 actionable tasks: 20 executed, 2 up-to-date
```

I have to find what does make the difference here.

**Comment by tchiotludo** [comment]
look at here : https://github.com/tchiotludo/akhq/runs/4423640449?check_suite_focus=true
You will see all the test that failed

**Comment by txs4444** [comment]
I fix some of the test - I hope all. You see it's hard because the test result depends on the test order - my `RecordRepositoryTest#produceAndConsumeRecordUsingJsonSchema` created new topic while producing a message as a result tests like `TopicControllerTest` failed.
Now I explicitly created this topic in `KafkaTestCluster` and updated the numbers there so all the test had the same topics regardless of the test order.

Could you please run the checks again? I'm feeling kind of blind because the tests passes locally but it is not necessary true for the checks on github.

**Comment by tchiotludo** [comment]
@txs4444, I know some kind of tricky this part ... 
I need to definitely change this behaviour one day ... 
But test passed now, thanks for this good one ;)

**Comment by tchiotludo** [comment]
And it's merged, thanks a lot :)

**Pull request merged**
