### PR TITLE
increase partitions of a topic

### PR DESCRIPTION
**Pull request by shivasheeshyadav**
#294 Added API to increase # of partitions of a topic.

### CODE REVIEW

**Comment by tchiotludo** [comment]
Sorry for the very very late review ... 
Seems to be fined, maybe just add some check on the current partition wanted that must be > than current one to avoid 500 error and have a 422 instead ?

**Comment by shivasheeshyadav** [comment]
@tchiotludo Sure. I'll add those checks and update the PR.

**Comment by tchiotludo** [comment]
Now that new ui is here, we can go with this one.

@shivasheeshyadav: don't you want to continue on these and add the ui on the new ui ?

- You can remove all the part from the old ui (toast mostly) and rebase from dev.  
- The better on this part is to use the topic config tab and add a new input with a dedicated button to allow increase of partition 

What do you think about that ?

**Comment by tchiotludo** [comment]
hey @shivasheeshyadav, maybe you can only rebase from dev branch and i will merge and finalize the feature ?

**Comment by tchiotludo** [comment]
@shivasheeshyadav can you rebase with dev branch ? 
Your commit is too old in order to merge it.
I could simply paste the code but I want to keep you as owner of the commit in order to keep your contribution

Thanks

**Comment by ebrard** [comment]
@shivasheeshyadav Any update on this? That's a very interesting feature for us as well.

**Comment by nickstatka777** [comment]
Hello! Is any update here? This is a very needful feature.

**Comment by tchiotludo** [comment]
@shivasheeshyadav abandon this one.
another PR are welcome

**Pull request closed without merging**
