### PR TITLE
feat(security): Add checkov for security check

### PR DESCRIPTION
**Pull request by ThomasSanson**
it should be added to the github workflow as a warning for now

### CODE REVIEW

**Comment by tchiotludo** [comment]
Don't understand the goal of this one? We don't have terraform inside the repo ?

**Comment by ThomasSanson** [comment]
@tchiotludo Checkov scans these IaC file types:

- Terraform (for AWS, GCP, Azure and OCI)
- CloudFormation (including AWS SAM)
- Azure Resource Manager (ARM)
- Serverless framework
- Helm charts
- Kubernetes
- Docker

It will make a little duplicate with kics indeed but I find it complementary 😇

**Comment by tchiotludo** [comment]
Does it offered more than dependabot for the both of them? 
Having many scan solution will suffer to have duplicated notification than it's really hard and take a lot of time for maintainer to analyse.

**Comment by ThomasSanson** [comment]
Yes I understand and share (but it doesn't seem to me that dependabot does all this).

That's why I advise to put only in warning

**Comment by tchiotludo** [comment]
I've already this activated : 
- https://codeql.github.com/ activated [here](https://github.com/tchiotludo/akhq/blob/dev/.github/workflows/codeql-analysis.yml) 
- [Dependabot alerts](https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts)

**Comment by ThomasSanson** [comment]
Hum 🤔, if you find it not necessary, feel free to refuse the 2 pull requests, I would not be offended 😇

I don't know codeql and I don't know how to access the results locally, I'll look into it when I have time 😅

Thanks for this discovery

**Comment by tchiotludo** [comment]
I'm not refusing them, I just challenging them :smile: 
Too many alert is not a life :skull: 

If you have a fully automated solution like dependanbot (create a PR, launch test), i'm ok with that :+1:

**Comment by ThomasSanson** [comment]
I'll look into running this via dependabot

**Comment by tchiotludo** [comment]
will no support for now, thanks!

**Pull request closed without merging**
