### PR TITLE
fix(groups): check permissions on cluster/resource for actions on consumer groups (#1936)

### LINKED ISSUE #1936: Missing checks for permission on GroupController
With the following role definitions:
```yaml
      group-read:
        - resources:
            - CONSUMER_GROUP
          actions:
            - READ
      offset-reset:
        - resources:
            - CONSUMER_GROUP
          actions:
            - UPDATE_OFFSET
            - DELETE_OFFSET
```
and the following group definitions:
```yaml
      akhq-reader:
        - role: group-read
      akhq-manager:
        - role: offset-reset
          patterns:
            - ^myconsumergroup.*$
```
a user assigned to both groups (akhq-reader and akhq-manager) can update the offset of any and all topics, even when they're not matching the pattern of "_^myconsumergroup.*$_".

Most of the controllers are implementing permission checks by callig `AbstractController#checkIfClusterAndResourceAllowed`. This checks seem to be missing in the `GroupController`.

### PR DESCRIPTION
**Pull request by alwibrm**
Check permissions on cluster/resource in `GroupController`, similar to i.e. `TopicController`.

Fixes #1936.

### CODE REVIEW

**Review by AlexisSouquiere — APPROVED** [review]
LGTM. Thanks for catching this !

**Comment by alwibrm** [comment]
@AlexisSouquiere Anything that has to be done to get this merged? This is hindering us from rolling out a feature.

**Comment by AlexisSouquiere** [comment]
@tchiotludo can you merge it please if it’s ok for you ?

**Comment by alwibrm** [comment]
Hi @tchiotludo, we're still waiting for this to be released. Is foreseeable when this could be the case? :)

**Comment by alwibrm** [comment]
Hi @tchiotludo, are there any plans for a new AKHQ release? We're still waiting for this fix in a release version.

**Pull request merged**
