### PR TITLE
Adding download all messages feature

### LINKED ISSUE #1487: Ability to download all of a topic's messages
Previous issue for creating download functionality: #1183, PR: #1384

The current download implementation only downloads whatever is in the React state. It would be good if we could download all of the data from a topic irregardless of the displayed messages.

### PR DESCRIPTION
**Pull request by AlexisSouquiere**
Fix #1487 

- [x] Follow Micronaut [guidelines](https://docs.micronaut.io/latest/guide/index.html#transfers) about sending large amount of data (StreamedFile + PipedInputStream/PipedOutputStream for custom datasource)
- [x] Add button to download all the messages next to the filters
image
- [x] Add a warning message to warn people about the amount of data 
image
- [x] Take into account the filters set by the users

Tested locally with a topic of 600K records, downloaded a 220Mb file in less than 1min

Downloaded file format is the following:
image
With Avro messages 
image
With Tombstone
image

Feedback is appreciated 😄

### CODE REVIEW

**Comment by tchiotludo** [comment]
@AlexisSouquiere merged before, sorry :sweat_smile:

**Comment by tchiotludo** [comment]
@AlexisSouquiere you want to add extra commit on that one to handle `endTimestamp`?

**Comment by AlexisSouquiere** [comment]
It's fine for me I took into account the new filter on the download endpoint :)
PR is ready

**Comment by arindampatra33** [comment]
@tchiotludo  @AlexisSouquiere This commit added a @JsonIgnore to Topic field of Record , this is breaking the tail functionality

**Comment by AlexisSouquiere** [comment]
@arindampatra33 thanks for the alert. I will check and fix it

**Comment by arindampatra33** [comment]
@AlexisSouquiere  its failing with below error  in the UI when its trying to read topic.data 
I guess you have to revert the JsonIgnore topic is an important field 

Tail.jsx:398 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at rowId (Tail.jsx:398:33)
    at Table.jsx:519:17
    at Array.forEach (<anonymous>)
    at o.value (Table.jsx:517:10)
    at Wa (react-dom.production.min.js:182:192)
    at Ba (react-dom.production.min.js:181:224)
    at Ss (react-dom.production.min.js:263:490)
    at vc (react-dom.production.min.js:246:265)
    at mc (react-dom.production.min.js:246:194)

**Comment by arindampatra33** [comment]
@AlexisSouquiere  If you added it just to have lesser number of columns in the downloaded data , you can create a new model and populate. from Record data

**Pull request merged**
