### PR TITLE
Helm Example - Basic Auth and AWS MSK

### PR DESCRIPTION
**Pull request by alexvaque**

### CODE REVIEW

**Comment by tchiotludo** [comment]
hey @alexvaque, maybe you can add this on doc instead of values? I have the feeling that it will be **more** visible ?

**Comment by alexvaque** [comment]
Mmm, Do you mean a kind of "https://github.com/tchiotludo/akhq/blob/dev/docs/docs/configuration/helm.md" ?

like you did with 

https://github.com/tchiotludo/akhq/blob/dev/docs/docs/configuration/docker.md

**Comment by tchiotludo** [comment]
Yes maybe, what do you think?

**Comment by alexvaque** [comment]
yes, make sense and is aligned with the repo doc. So I could try to explain the helm creation and maybe I can put embedded in the .md my example that could help other people

**Comment by alexvaque** [comment]
Done, please felt free to update the text or the example.

**Pull request merged**
