### PR TITLE
WIP: New React UI

### PR DESCRIPTION
**Pull request by polarising-java**
Added Live Tails
Remove duplicate CSS
Fix bugs

### CODE REVIEW

**Comment by dblooman** [comment]
Hey, curious whether this include any design changes?

**Comment by tchiotludo** [comment]
@dblooman, not a really big change on the ui for now, just the left menu is redesign, but the main content is almost the same. 
The goal of this biggest change is mostly to have a powerful ui than the current static one.

**Comment by dblooman** [comment]
Awesome, I would like to add a few company specific changes, colours, fonts etc and a light mode

**Comment by tchiotludo** [comment]
Ok 👍
FYI, the light theme, a PR (on the new ui) will be really appreciate.
For customizing the style, a PR (also on the new ui) that allow injection of custom css will be accepted.
Like you want 👍

**Comment by dblooman** [comment]
That was my thinking, make it easy for someone to take the docker image an add a single override file for CSS. I will fork from this branch  👍

**Comment by tchiotludo** [comment]
done in: https://github.com/tchiotludo/akhq/commit/26650087f3a46033e7fe64875c2f4ec3ea0ba60a

**Pull request closed without merging**
