### PR TITLE
feat: reduce security vector attack: remove curl; refact run scripts

### PR DESCRIPTION
**Pull request by vutkin**

### CODE REVIEW

**Review by tooptoop4 — APPROVED** [review]

**Comment by tchiotludo** [comment]
Yes, I can, but after my holidays 😎
IMO, I would prefer to keep curl and update all package to avoid cve

**Comment by vutkin** [comment]
@tchiotludo could you please review/merge a PR?
Does it make sense to create 2 images: -slim prefixed and regular with curl and other vulnerable tools (just joking)?

**Comment by vutkin** [comment]
As well we could switch to UBI image: registry.access.redhat.com/ubi8/openjdk-11:1.13

**Comment by vutkin** [comment]
> could you please review/merge a PR?
> Does it make sense to create 2 images: -slim prefixed and regular with curl and other vulnerable tools (just joking)?

@tchiotludo could you please review?

**Comment by tooptoop4** [comment]
@vutkin after 'les vacances' time 🌞 🍹

**Comment by tchiotludo** [comment]
@vutkin you change too many things in 1 PR that is not related: 
- add a ubi image not used 
- moved of entrypoint & akhq files, why ? just preference matters it's seems, breaking change  
- changed of user on the docker image: Breaking change 
- removed of healthcheck: Breaking change

We can't merged this one, sorry

**Pull request closed without merging**
