### PR TITLE
fix(helm): Use toYaml Go template for configmap

### PR DESCRIPTION
**Pull request by AnatomicJC**

### CODE REVIEW

**Comment by tchiotludo** [comment]
agree with that :) 
It wil be better but we need to be consistent, can you make the change everywhere (secrets, ...) ?

**Comment by AnatomicJC** [comment]
Hi @tchiotludo 

I updated the `values.yaml` file accordingly.

I also replaced `indent` with `nindent`. Do you see other things to update ?

**Comment by tchiotludo** [comment]
`configuration` is also yml and can't be use as yaml in values

**Comment by AnatomicJC** [comment]
I reverted my last commit about `indent` and `nindent`
I tested on a local cluster and configmap seems ok now. What do you think ?

**Comment by tchiotludo** [comment]
perfect, thanks :)

**Comment by AnatomicJC** [comment]
Thanks to you for this project :+1:

**Pull request merged**
