### PR TITLE
Configure mechanism OAUTHBEARER

### PR DESCRIPTION
**Pull request by ericmagna**
Modify README.md on #591 issue.

### CODE REVIEW

**Review by kc89rst — APPROVED** [review]
Can you include those libraries in the default implementation available as Docker images?

**Comment by ericmagna** [comment]
I need to answer your request because I do not know how to do.
Can you explain to me how I have to integrate these libraries in a docker image for AKHQ ?
Thank.

**Review by kc89rst — COMMENTED** [review]
I’m not a maintainer. If you will add the 2 oauth libraries like you describe in README.md they will pe part of the built jar file which (I assume) will be released with a new version here: https://hub.docker.com/r/tchiotludo/akhq We are currently using a local image build in our project and would love to switch back to the official one.

**Comment by tchiotludo** [comment]
hey @ericmagna 
just add directly the depends on build.gradle please 
```
// strimzi
implementation group: 'io.strimzi', name: 'kafka-oauth-common', version: '0.7.0'
implementation group: 'io.strimzi', name: 'kafka-oauth-client', version: '0.7.0'
````
It will be available for everyone and just keep the configuration on readme please

**Comment by ericmagna** [comment]
I modify readme.md and dependencies strimzi in build.gradle.

**Comment by tchiotludo** [comment]
@ericmagna I think you forgot to commit the `build.gradle`. 
Also you can remove the part with 
> It is necessary to compile AKHQ to integrate the Strimzi libraries.
Sinice the libs will be included on the final image ! 

Thanks

**Comment by ericmagna** [comment]
conflict is resolved.

on branch ericmagna-patch-#591, i change build.gradle et readme.md.

check failed on autobuild and i have no knowledge on gradle.

**Comment by tchiotludo** [comment]
Sorry to bother you, but your PR is weird... 
The `build.gradle` is not on the [files changed](https://github.com/tchiotludo/akhq/pull/615/files) and the `README.md` contains a lot of stuff i'm not sure I want to merged.
Maybe you can start clean new one from `dev` branch ? 

The build error is because the unit test are flakky, don't bother you for that, I retry it and it's green now :)

**Comment by ericmagna** [comment]
close this pr to create other.

**Comment by ericmagna** [comment]
pr is #619.

**Pull request closed without merging**
