### PR TITLE
GenericRecord to JSON serialization with correct decimal output

### PR DESCRIPTION
**Pull request by rigadon**
Bugfix of GenericRecord to JSON serialization for decimals.

### CODE REVIEW

**Comment by tchiotludo** [comment]
Seems to be strange bug fix ! 
Can you tell me more ? 

The only goal of this PR is to have the right number of decimal right ? 
Before it was displayed as float ?

**Comment by rigadon** [comment]
The problem here is that we are working with GenericRecord and it is unable to serialize decimals correctly because inside of the record we have an array of bytes. It causes an issue with JSON we display. For instance, in you look at https://github.com/tchiotludo/akhq/blob/3d3b2d67bb4077e3cefdc43fff15834f8543c763/src/test/java/org/akhq/modules/AvroToJsonSerializerTest.java and try to serialize a generic record that contains Dog avro to string via `toString` method then you will receive a string like `{"id": 10, "name": "Tiger", "weight": "\u0004\u0010"}`. At the same time with the change, we will be able to detect those decimal values based on schema an serialize that record to `"{\"id\":10,\"name\":\"Tiger\",\"weight\":\"10.40\"}"`.

**Comment by tchiotludo** [comment]
Really strange ! I'll try your PR !
without your PR : 
image

With your PR : 
image

I have better result without ! 
To test it, i simply produce a message with Dog schema.

The decimal part (max: 2) is not respected but the value is correct. 
Your PR seems to display the wrong value.

Maybe I lost a thing ?

**Comment by rigadon** [comment]
Unfortunately, you faced another defect AKHQ has. It looks like you submitted a message via the interface AKHQ has and the decimal was provided as a string. In this case, in the current implementation, the string("10.40") will be serialised to an array of bytes and deserialised from the array of bytes to the string and it looks like the value is correct in Kafka but in fact, if you deserialise that array of bytes to decimal you will receive a completely different number(2112617318.88). Basically, that happened with you and I understand that it is a bit confusing. I did a test when I produced a Dog avro message to a topic via another application and tried to read that message with two different implementations of AKHQ.

With the current implementation I got:
image

And with the fix I made I got:
image

Of course, we also need to fix an issue you have faced but I expect it to be fixed in another PR.

**Comment by tchiotludo** [comment]
OK make sense ;) 
Thanks for the PR :) 

I add an issue for the produce, feel free to take it ;)

**Pull request merged**
