### PR TITLE
Fix LDAP example in docs.

### PR DESCRIPTION
**Pull request by AntonSmolkov**
Fix according to this issue and comment
https://github.com/tchiotludo/akhq/issues/336#issuecomment-663367630

We have spent hours struggling with ldap groups containig dots.
With this (ugly, i know) approach no one will ever face this tricky problem.

Also, example from documetation with testing server does not work at all for now, this PR fixes this too.

### CODE REVIEW

**Comment by tchiotludo** [comment]
Hi, 
What version of akhq do you use ? 

One wrong thing in akhq is `README.md` is based on `dev` branch and we have changed the way all of this works for next release with BC changed. 

Seems that your main issue here !

**Comment by AntonSmolkov** [comment]
Latest image from DockerHub. Guess it's 0.15.0

**Comment by AntonSmolkov** [comment]
0.15.0 tag still contains ldap example which does not work with non-lowercase ldap-gropus

**Comment by tchiotludo** [comment]
0.16.0 change the configuration and this PR will not work. 
Maybe you can update the PR with last version, there is some interesting MS ActiveDirectory comment I think

**Comment by tchiotludo** [comment]
closing for inactivity

**Pull request closed without merging**
