### PR TITLE
Feat audit

### PR DESCRIPTION
**Pull request by ebrard**
This PR adds audit information about any Kafka related actions that performs a change (creation, modification, deletion). Out of scope are schema registry and connect.

The audit event are triggered to a configurable kafka cluster which needs to be one of the cluster under akhq managament.

This addresses the issue [1474](https://github.com/tchiotludo/akhq/issues/1474).

Tests on the `TopicRepository` have been slightly modified so that topics which are created during audit tests are not considered.

### CODE REVIEW

**Comment by ebrard** [comment]
@tchiotludo Ok I found how I could add tests.

**Comment by ebrard** [comment]
@tchiotludo Do you think you could review this PR soon? That's a feature we will need to rely on.

**Comment by tchiotludo** [comment]
Seems to be a good one, but I think you should use a better enum:
```java
    public enum ActionType {
        UPDATE_OFFSETS_CONSUMER_GROUP,
        DELETE_OFFSETS_CONSUMER_GROUP,
        DELETE_CONSUMER_GROUP,
        NEW_TOPIC,
        CONFIG_CHANGE,
        INCREASE_PARTITION,
        DELETE_TOPIC
    }
``` 
could be: 
```java
    public enum ActionType {
        CONSUMER_GROUP_UPDATE_OFFSETS,
        CONSUMER_GROUP_DELETE_OFFSETS,
        CONSUMER_GROUP_DELETE,
        TOPIC_CREATE,
        CONFIG_CHANGE, //?? 
        TOPIC_INCREASE_PARTITION,
        TOPIC_DELETE
    }
``` 
also is it possible to handle others one? (schema, etc ...)?

**Comment by jonasvoelcker** [comment]
Hey @tchiotludo, as I changed everything towards vite, vitest and jsx it would be good to know whether this feature will be part of the 0.25.0 or not. Anyways this will need an upgrade to fit in our new frontend setup. FYI: @AlexisSouquiere

**Comment by tchiotludo** [comment]
@jonasvoelcker it seems to be only backend update, does this PR has impact on the vite upgrade?

**Comment by jonasvoelcker** [comment]
@tchiotludo You are right, I thought there were some js-files, but it's java instead. Next time I need to scroll to the right ^^

**Comment by ebrard** [comment]
@tchiotludo speaking of which, any deadline for the PR to be part of the next release? I'll work on it again next week.

**Comment by ebrard** [comment]
Ok, I've renamed the enum values. I'll see what I can do about the schema and connect components.

**Comment by ebrard** [comment]
Hey @tchiotludo I've added audit for the schema registry and the kafka connect clusters. Let me know what you think.

**Pull request merged**
