### PR TITLE
Fix: IndexOutOfBoundsException thrown in topics view when changing to…

### PR DESCRIPTION
**Pull request by EdwinFajardoBarrera**
… cluster with fewer pages.

Closes issue #835

When the cluster is changed now it forces the state to have pageNumber equals to 1 to avoid failure if the new cluster has fewer pages than the old one.

### CODE REVIEW

**Comment by EdwinFajardoBarrera** [comment]
@tchiotludo If you can review my PR I would appreciate it, I await your comments, greetings!

**Comment by tchiotludo** [comment]
@EdwinFajardoBarrera it seems to be a good fix !
Is it possible to handle this on list please ?

**Comment by EdwinFajardoBarrera** [comment]
> @EdwinFajardoBarrera it seems to be a good fix ! Is it possible to handle this on list please ?

Sorry I don't get you, how can I help you?

**Comment by tchiotludo** [comment]
For example this [one](https://github.com/tchiotludo/akhq/blob/dev/client/src/containers/Connect/ConnectList/ConnectList.jsx#L52), I've the feeling the bug is also here ?
May you have a look on all pages with pagination ?

**Comment by EdwinFajardoBarrera** [comment]
> 

For sure, take it for granted

**Comment by EdwinFajardoBarrera** [comment]
@tchiotludo I'm having issues configuring multiple clusters, actually, this is working

- [ ]  Kafka-0
- [ ]  Schema-registry-0
- [ ]  Connector-0 ** Docker container stops
- [ ]  Kafka-1
- [ ]  Schema-registry-1
- [ ]  Connector-1

I leave my docker-compose-multiple-cluster.yml file: https://codeshare.io/1YbNvX

My application-dev.yml connections are as follows:

```
akhq:
  connections:
    local-0:
      properties:
        bootstrap.servers: "localhost:9092"
      schema-registry:
        url: "http://localhost:8085"
      connect:
      - name: "connect-0"
        url: "http://localhost:8083"
    local-1:
      properties:
        bootstrap.servers: "localhost:9072"
      schema-registry:
        url: "http://localhost:8075"
      connect:
      - name: "connect-1"
        url: "http://localhost:8084"

```

Thanks for your help

**Comment by tchiotludo** [comment]
can you give the log of the failed connect please ? 
I don't see any reasoon like that

**Comment by EdwinFajardoBarrera** [comment]
> can you give the log of the failed connect please ? I don't see any reasoon like that

I just got this:

image

image

I see that the first connect instance that I select makes the other shutdown.

```
[2021-12-22 19:16:37,849] INFO [Worker clientId=connect-1, groupId=kafka-connect-1] Session key updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder)

Dec 22, 2021 7:16:35 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime

WARNING: A provider org.apache.kafka.connect.runtime.rest.resources.RootResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.apache.kafka.connect.runtime.rest.resources.RootResource will be ignored.
```

**Comment by tchiotludo** [comment]
You have a mistake corrected here : https://codeshare.io/1YbNvX
But I'm not really sure you're setup is possible like that (on the same docker host / multiple kafka, zookepper), I've the feeling they will try to make a unique cluster

**Comment by EdwinFajardoBarrera** [comment]
> For example this [one](https://github.com/tchiotludo/akhq/blob/dev/client/src/containers/Connect/ConnectList/ConnectList.jsx#L52), I've the feeling the bug is also here ? May you have a look on all pages with pagination ?

I just checked and fixed [this](https://github.com/tchiotludo/akhq/blob/dev/client/src/containers/Connect/ConnectList/ConnectList.jsx#L52) and apparently, there is no other page (where using pagination) that replicates this bug.

**Comment by tchiotludo** [comment]
THanks for having a deeper look :+1:

**Comment by EdwinFajardoBarrera** [comment]
> THanks for having a deeper look 👍

No problem, let me know if there is another issue with priority (If this is in the backend is better for me)

**Comment by tchiotludo** [comment]
https://github.com/tchiotludo/akhq/labels/backend you will find the backend issue, feel free to pick up one that sound interesting for you

**Pull request merged**
